# Generated by Django 4.2.4 on 2023-11-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pay', models.CharField(choices=[('TO_COMPANY', 'TO_COMPANY'), ('TO_USER', 'TO_USER')], default='TO_COMPANY', max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('date_paid', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
