# Generated by Django 4.2.4 on 2023-11-06 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='animation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_animations', to='products.animation'),
        ),
    ]
